name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.dockerhubusername }}/webserver:latest
    - name: Create new Tag
      run: docker tag webserver:latest ${{ secrets.dockerhubusername }}/webserver:$(date +%s)
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.dockerhubusername }}
        password: ${{ secrets.dockerhubpat }}
